# Generated by Django 4.2.1 on 2023-07-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listind_id',
            new_name='listing_id',
        ),
    ]
